### PR TITLE
Start with clock in stopped state (was ClockChecker)

### PR DESCRIPTION
**Pull request by j-fu**
* Allow to check if the clock is running
* Do bookkeeping of the number of checks

See https://github.com/fonsp/Pluto.jl/issues/476

### CODE REVIEW

**Comment by fonsp** [comment]
The Clock already returns the number of ticks:
```julia
@bind num_ticks Clock()
```

```julia
collect(1:num_ticks)
```

**Comment by fonsp** [comment]
There are lots of these kinds of reactive mutability problems, and each requires a different creative solution. I think that this is too specific (and complicated) to include in PlutoUI. It would be more useful to write documentation to explain how to use `Ref` and reactive links to solve these puzzles yourself.

Another thing is that this promotes non-declarative programming. A declarative solution would be to use a precomputed animation (#26) or a GIF - this is a much simpler concept. You can also use memoization to write it as a function of (interactive) time. It sounds like you want to optimize the speed or memory usage, but is that really necessary?

**Comment by j-fu** [comment]
I accept that you see this as too complicated, after all it's a matter of taste... May be I'll find an simpler way which doesn't need such a struct.

As for declarative programming:  It is all about the way time dependent results which can take some time for being computed are visualized. What I described is essentially a kind of iterator which produces time dependent results from an initial state. Whether they have been stored or are actually computed IMHO does not matter that much. However, storing may be expensive (3D PDEs), and waiting for a gif being produced for  a longer calculation without any information (graphical or not) about the evolving state feels awkward like a windows boot after a system update... But I also grew up imperaratively, so I will check my mindset here...
 
Ultimately I want to use GPU accelerated graphics as in Makie or MeshCat for showing produced or stored results.  Admittedly both seem to have concepts of updating a scene from within the for loop (need to check if this really works). In the moment both lack some visualization options, so PyPlot is in the list, too.

... what do you think about the clock state stopped by default after load ?

**Comment by fonsp** [comment]
> ... what do you think about the clock state stopped by default after load ?

Yes! We should add this property, and let's actually make it the default.

> Ultimately I want to use GPU accelerated graphics as in Makie or MeshCat for showing produced or stored results.

This is definitely on my mind, I also want this to be possible. The MeshCat demo you sent is promising, and also the simon danisch ecosystem, but (currently) they both run their own HTTP server on a separate port, which means that it does not work over SSH, binder or GitHub codespaces (without forwarding the extra port), and I think/hope that these are "the future". Ideally they could both use Pluto as a proxy.

I am collaborating with Shashi Gowda and Sebastian Pfitzner on this problem - we hope to create a new `Abstract*` package that anyone can use to _describe_ how their types can be visualized, and some other things. It will include this proxy idea.

Our design document is here:
https://docs.google.com/document/d/1_KJtlB0EyM8ytRzqngQBTArQLfNLPj70mDTywSVbghA/edit?usp=sharing
Feel free to join the discussion and write a paragraph about 3D viz.

> both seem to have concepts of updating a scene from within the for loop

This is a problem, because it breaks the all important goal: _"At any instant, the program state is completely described by the code you see."_

I think that the solution could be lazy lists. The basic use case:
```julia
Animation([expensive_result(t) for t in 1:100])
```
Could be made runtime/memory efficient by describing the frames using a lazy map:
```julia
Animation(map(expensive_result, @lazy 1:100))
```
Here, `Animation` is called immediately, and can generate frames lazily, when the UI requests one.

In your example, the simulation depends on the previous step, which makes it a trickier `accumulate`/`reduce` problem:
```julia
Animation(accumulate(advance, @lazy 1:100, init=x0))
```
with
```julia
function advance(old_solution::Array, t::Number)::Array
	...
	return new_solution
end
```

**Comment by j-fu** [comment]
> This is definitely on my mind, I also want this to be possible. The MeshCat demo you sent is promising, and also the simon danisch ecosystem, but (currently) they both run their own HTTP server on a separate port, which means that it does not work over SSH, binder or GitHub codespaces (without forwarding the extra port), and I think/hope that these are "the future". Ideally they could both use Pluto as a proxy.

Great that you see this in a similar way!

They both use three.js in the background. From the first tests I have the impression that MeshCat has much better performance, and each WGLMakie plot eats up one CPU core. When I'll find time I'll test this more and tell Simon...  May be it is due to different ways to communicate data to three.js.

> 
> I am collaborating with Shashi Gowda and Sebastian Pfitzner on this problem - we hope to create a new `Abstract*` package that anyone can use to _describe_ how their types can be visualized, and some other things. It will include this proxy idea.
> 
> Our design document is here:
> https://docs.google.com/document/d/1_KJtlB0EyM8ytRzqngQBTArQLfNLPj70mDTywSVbghA/edit?usp=sharing
> Feel free to join the discussion and write a paragraph about 3D viz!
I had a look - I am not that much in this javascript technology stuff (dabbled with three.js some time ago), so I am not sure if can contribute that much.  However I will prepare a gist on my viewpoint, and provide the link.

**Comment by j-fu** [comment]
Ok accept the design decision to go without additonal methods around the clock, Would be nice thoug to allow initial state stopped (may be as an option).

**Pull request merged**
