### PR TITLE
Colored with_terminal() with nice styling (I think)

### LINKED ISSUE #88: Colored with_terminal output
by @Roger-luo: the `with_terminal` output should be colored using ANSI codes.

We can use https://github.com/drudru/ansi_up for that!

### PR DESCRIPTION
**Pull request by dralletje**
Fixes #88 

Pweeeaaaaaaase @fonsp 

It looks so slick!!

image

image

### CODE REVIEW

**Comment by fonsp** [comment]
Beautiful!

**Comment by fonsp** [comment]
Are we using IOCapture instead of Suppressor? Remove the dependency?

**Comment by fonsp** [comment]
You can merge this yourself, let me know if you need help publishing the new release

**Comment by dralletje** [comment]
> You can merge this yourself, let me know if you need help publishing the new release

:O

**Comment by fonsp** [comment]
released https://github.com/fonsp/PlutoUI.jl/commit/0be72d15091703eec664bc67d35608b9547655ec

**Comment by ilyagr** [comment]
In think this has a bug with the way it calls `AnsiUp`. See https://github.com/JuliaPluto/PlutoUI.jl/issues/196.

**Pull request merged**
