### PR TITLE
Adds support for microphone input

### PR DESCRIPTION
**Pull request by mthelm85**
Hallo, Fons!

I've added support for the microphone input but I'm certain it will need some additional work. With this PR, users can do:

```julia
@bind audio Microphone()
```

This returns an array that constantly updates with the audio streaming from the microphone. To visualize the data, you might do something like this:

```julia
using Plots, SampledSignals

plot(domain(SampleBuf(Array(audio), 44100)), SampleBuf(Array(audio), 44100), legend=false, ylims=(-1,1))
```

This (kind of) resolves issue #16 

Groetjes!

### CODE REVIEW

**Comment by fonsp** [comment]
The code contains merge conflicts, can you fix it?

**Comment by mthelm85** [comment]
Hmmm, on my end it says there are no conflicts..??? Should I re-submit the PR?

**Comment by fonsp** [comment]
Have a look: https://github.com/fonsp/PlutoUI.jl/pull/54/files#diff-6da3179d6a3c0401f3270d4b110b04845273bd9124eb0c4d42d649c84b517868R9

**Comment by mthelm85** [comment]
Okay, I think I fixed it. I'm not sure why sometimes when I create pull requests I get these lines inserted into my code (obviously it's due to my lack of understanding of Git/GitHub):

```julia
<<<<<<HEAD

>>>>>#some random string
```

**Comment by mthelm85** [comment]
bump. Is there still a merge conflict?

**Comment by fonsp** [comment]
Thanks! Can you move it to a separate file?

**Comment by mthelm85** [comment]
How's this?

**Comment by mbauman** [comment]
This is great!  What would be needed to resurrect this PR?  I recently used this for a training and would love to have it in PlutoUI.jl.

https://gist.github.com/mbauman/f50e0fcc20a2a16fd7e9a015f9cc54c1

**Comment by fonsp** [comment]
Hey! I think the TODOs are:
- Rewrite to use HypertextLiteral
- Place in separate file
- Think about what value type to return: Vector{UInt8} or something from the audio packages? (With AbstractPlutoDingetjes.Bonds.transform_value)
- Implement a default value with AbstractPlutoDingetjes.Bonds.default_value

**Pull request closed without merging**
