### PR TITLE
Restrict height of  result of with_terminal()

### PR DESCRIPTION
**Pull request by j-fu**
Hi, would be good to prevent the with_terminal() output from overflowing the screen...
Is it possible in css to set the scrollbar position to "completely down" ?

### CODE REVIEW

**Comment by dralletje** [comment]
There is this answer on stackoverflow https://stackoverflow.com/a/44051405/2681964 , or even easier, this comment https://stackoverflow.com/questions/18614301/keep-overflow-div-scrolled-to-bottom-unless-user-scrolls-up#comment79201655_44051405 .

I was also looking at the other styling... can I get rid of the pink border? 😁 Seemed kinda random, you have a specific reason for the border radius and the thick border?

**Comment by fonsp** [comment]
Haha the pink border was added by me - I'm happy as long as the border is thick, to make it look like a CRT monitor.

**Comment by dralletje** [comment]
Oh @fonsp .... hahahaha

@j-fu Now the stderr and stdout outputs are reversed. I don't mind too much but just letting you know :)

**Comment by j-fu** [comment]
... for me they land in the same stream due to the ConsoleLogger(stdout) thing which I like. I remember having seen them in different streams (white / red tough)... May be something is not fully understood here. With the scrollbar down, errors should either come in together with stdout or at the end.

For the color: this was the vt100: https://www.vintagecomputer.net/browse_thread.cfm?id=618 so I tried to pick someting like that :)

**Comment by j-fu** [comment]
merged with master, still would be nice to have this...

**Comment by fonsp** [comment]
Yay thank you!

**Pull request merged**
